### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by xiaotian1339** [fkunde/Fkun-Book-keeping#23]
安装的时候提示，创建默认用户失败……
然后注册的时候提示   写入数据库时出错!增加默认分类出错！
求解决方法
Ubuntu20.04  LAMP

**Comment by fkunde** [comment]
感谢提供测试。
刚自己本地试一下但并没有出现相同的问题。环境：XAMPP

建议：
1.删除旧数据库
2.检查config.php是否配置正确
3.检查数据库权限

**Comment by xiaotian1339** [comment]
想问一下mysql的版本是多少呢？我使用的是mysql8.0，会不会和新版更新的一些东西有冲突呢？

**Comment by fkunde** [comment]
本地测试环境
=================================
服务器： 127.0.0.1 via TCP/IP
服务器类型： MariaDB
服务器连接: SSL未被使用 文档
服务器版本： 10.4.14-MariaDB - mariadb.org binary distribution
协议版本： 10
用户： root@localhost
服务器字符集： UTF-8 Unicode (utf8mb4)
=================================
Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.10
数据库客户端版本： libmysql - mysqlnd 7.4.10
PHP 扩展： mysqli 文档 curl 文档 mbstring 文档
PHP 版本： 7.4.10

**Comment by fkunde** [comment]
今天用PHP8 环境试了一下，确实出现了同样的问题。
已修复。
